"""
Student Model for VPP Optimization.

MLP that imitates the Perfect Foresight Teacher's dispatch decisions.
Trained on (state, features) → action pairs generated by the MPC loop.

Architecture (from IMPLEMENTATION_SPECS.md Section 3):
    Input(7) → Linear(64) → ReLU
             → Linear(64) → ReLU
             → Linear(32) → ReLU
             → Linear(1)  → Tanh × P_max
"""

from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset


# Default feature columns matching data generation output
FEATURE_COLUMNS = [
    "hour_sin",
    "hour_cos",
    "price_current",
    "price_avg_4h",
    "net_load",
    "soc",
    "dow_sin",
]

TARGET_COLUMN = "power_setpoint"


class VPPStudentModel(nn.Module):
    """MLP student model that imitates the perfect foresight teacher.

    Architecture follows IMPLEMENTATION_SPECS.md:
    - 3 hidden layers with ReLU activation
    - Output bounded to [-P_max, +P_max] via Tanh scaling

    The Tanh output ensures the model can never predict physically
    impossible power values, regardless of input.

    Args:
        input_dim: Number of input features (default: 7)
        hidden_dims: List of hidden layer sizes (default: [64, 64, 32])
        max_power: Maximum battery power in kW for output scaling

    Example:
        >>> model = VPPStudentModel(input_dim=7, max_power=50.0)
        >>> x = torch.randn(32, 7)  # batch of 32
        >>> y = model(x)            # shape: (32, 1), range: [-50, 50]
    """

    def __init__(
        self,
        input_dim: int = 7,
        hidden_dims: List[int] = None,
        max_power: float = 50.0,
    ):
        super().__init__()

        if hidden_dims is None:
            hidden_dims = [64, 64, 32]

        self.input_dim = input_dim
        self.hidden_dims = hidden_dims
        self.max_power = max_power

        # Build hidden layers
        layers = []
        prev_dim = input_dim
        for h_dim in hidden_dims:
            layers.append(nn.Linear(prev_dim, h_dim))
            layers.append(nn.ReLU())
            prev_dim = h_dim

        self.hidden = nn.Sequential(*layers)

        # Output layer: single scalar power prediction
        self.output_layer = nn.Linear(prev_dim, 1)

        # Initialize weights (Xavier uniform for ReLU networks)
        self._init_weights()

    def _init_weights(self) -> None:
        """Initialize weights using Xavier uniform."""
        for module in self.modules():
            if isinstance(module, nn.Linear):
                nn.init.xavier_uniform_(module.weight)
                nn.init.zeros_(module.bias)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass.

        Args:
            x: Input tensor of shape (batch_size, input_dim)

        Returns:
            Power prediction of shape (batch_size, 1), bounded to [-P_max, P_max]
        """
        h = self.hidden(x)
        raw = self.output_layer(h)
        # Tanh scales output to [-P_max, P_max]
        return torch.tanh(raw) * self.max_power

    def predict(self, x: np.ndarray) -> np.ndarray:
        """Convenience method for numpy inference.

        Args:
            x: Input array of shape (n_samples, input_dim)

        Returns:
            Power predictions of shape (n_samples,)
        """
        self.eval()
        with torch.no_grad():
            tensor = torch.tensor(x, dtype=torch.float32)
            output = self.forward(tensor)
            return output.squeeze(-1).numpy()

    def count_parameters(self) -> int:
        """Count total trainable parameters."""
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

    def summary(self) -> str:
        """Return a model architecture summary string."""
        lines = []
        lines.append(f"VPPStudentModel (max_power={self.max_power} kW)")
        lines.append("=" * 50)

        total_params = 0
        for name, module in self.named_modules():
            if isinstance(module, nn.Linear):
                n_params = module.weight.numel() + module.bias.numel()
                total_params += n_params
                lines.append(
                    f"  {name:20s} Linear({module.in_features} → {module.out_features})"
                    f"  params={n_params:,}"
                )
            elif isinstance(module, nn.ReLU):
                lines.append(f"  {name:20s} ReLU")

        lines.append("  output activation:  Tanh × P_max")
        lines.append("=" * 50)
        lines.append(f"Total trainable parameters: {total_params:,}")
        return "\n".join(lines)


class VPPDataset(Dataset):
    """Dataset for VPP training data.

    Loads features and targets from CSV, with optional scaling.

    Args:
        csv_path: Path to training data CSV
        feature_columns: List of feature column names
        target_column: Target column name
        max_power: P_max for target normalization (if normalize_target=True)
        normalize_target: Whether to scale target to [-1, 1] by dividing by max_power

    Example:
        >>> dataset = VPPDataset("data/training_data.csv")
        >>> features, target = dataset[0]
        >>> print(features.shape, target.shape)  # torch.Size([7]) torch.Size([1])
    """

    def __init__(
        self,
        csv_path: str,
        feature_columns: Optional[List[str]] = None,
        target_column: str = TARGET_COLUMN,
        max_power: float = 50.0,
        normalize_target: bool = False,
    ):
        self.csv_path = csv_path
        self.feature_columns = feature_columns or FEATURE_COLUMNS
        self.target_column = target_column
        self.max_power = max_power
        self.normalize_target = normalize_target

        # Load data
        df = pd.read_csv(csv_path)

        # Extract features and target
        self.features = torch.tensor(
            df[self.feature_columns].values, dtype=torch.float32
        )
        targets = df[self.target_column].values.astype(np.float64)

        if normalize_target:
            targets = targets / max_power

        self.targets = torch.tensor(targets, dtype=torch.float32).unsqueeze(1)

    def __len__(self) -> int:
        return len(self.features)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.features[idx], self.targets[idx]

    @property
    def input_dim(self) -> int:
        """Number of input features."""
        return self.features.shape[1]

    @property
    def n_samples(self) -> int:
        """Number of samples."""
        return len(self.features)

    def get_feature_stats(self) -> dict:
        """Get feature statistics for normalization."""
        return {
            "mean": self.features.mean(dim=0),
            "std": self.features.std(dim=0),
            "min": self.features.min(dim=0).values,
            "max": self.features.max(dim=0).values,
        }

    def get_target_stats(self) -> dict:
        """Get target statistics."""
        return {
            "mean": self.targets.mean().item(),
            "std": self.targets.std().item(),
            "min": self.targets.min().item(),
            "max": self.targets.max().item(),
        }
