"""
Training Pipeline for VPP Student Model.

This module implements the supervised learning pipeline to train the Neural Network 
student on the dataset generated by the MILP teacher.

Key Design Decisions:
- Time-series split: Train on first 80% (days 0-292), Val on last 20% (days 293-365)
- Feature normalization: StandardScaler (mean=0, std=1)
- Target normalization: NONE (model outputs raw kW via Tanh × P_max)
- Loss: MSE in kW space
- Early stopping: patience=10 epochs on val loss
"""

import os
import pickle
import json
from dataclasses import dataclass, asdict
from typing import Dict, Optional, Tuple
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import logging

import sys
import os

# Add project root to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from src.vpp.learning.models import VPPStudentModel

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class TrainingConfig:
    """Training hyperparameters."""
    batch_size: int = 256
    learning_rate: float = 1e-3
    max_epochs: int = 100
    early_stopping_patience: int = 10
    lr_scheduler_patience: int = 5
    lr_scheduler_factor: float = 0.5
    device: str = "cuda" if torch.cuda.is_available() else "cpu"
    random_seed: Optional[int] = 42


class Trainer:
    """Training orchestrator for VPP Student Model."""
    
    def __init__(
        self,
        model: VPPStudentModel,
        train_loader: DataLoader,
        val_loader: DataLoader,
        config: TrainingConfig,
        scaler: StandardScaler
    ):
        """
        Args:
            model: VPPStudentModel instance
            train_loader: Training data loader
            val_loader: Validation data loader
            config: Training configuration
            scaler: Fitted StandardScaler for features
        """
        self.model = model.to(config.device)
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.config = config
        self.scaler = scaler
        self.device = config.device
        
        # Training components
        self.criterion = nn.MSELoss()
        self.optimizer = torch.optim.Adam(model.parameters(), lr=config.learning_rate)
        self.scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            self.optimizer,
            mode='min',
            factor=config.lr_scheduler_factor,
            patience=config.lr_scheduler_patience
        )
        
        # Training state
        self.history = {
            'epoch': [],
            'train_loss': [],
            'val_loss': [],
            'lr': []
        }
        self.best_val_loss = float('inf')
        self.best_model_state = None
        self.patience_counter = 0
        
    def train_epoch(self) -> float:
        """Train for one epoch."""
        self.model.train()
        total_loss = 0.0
        n_batches = 0
        
        for features, targets in self.train_loader:
            features = features.to(self.device)
            targets = targets.to(self.device)
            
            # Forward pass
            predictions = self.model(features)
            loss = self.criterion(predictions, targets)
            
            # Backward pass
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()
            
            total_loss += loss.item()
            n_batches += 1
            
        return total_loss / n_batches
    
    def validate(self) -> float:
        """Validate on validation set."""
        self.model.eval()
        total_loss = 0.0
        n_batches = 0
        
        with torch.no_grad():
            for features, targets in self.val_loader:
                features = features.to(self.device)
                targets = targets.to(self.device)
                
                predictions = self.model(features)
                loss = self.criterion(predictions, targets)
                
                total_loss += loss.item()
                n_batches += 1
                
        return total_loss / n_batches
    
    def train(self) -> Dict:
        """
        Execute full training loop with early stopping.
        
        Returns:
            Training history dictionary
        """
        logger.info(f"Starting training on {self.device}")
        logger.info(f"Config: {asdict(self.config)}")
        
        for epoch in range(self.config.max_epochs):
            # Train
            train_loss = self.train_epoch()
            
            # Validate
            val_loss = self.validate()
            
            # Learning rate scheduler step
            self.scheduler.step(val_loss)
            
            # Get current learning rate
            current_lr = self.optimizer.param_groups[0]['lr']
            
            # Record history
            self.history['epoch'].append(epoch + 1)
            self.history['train_loss'].append(train_loss)
            self.history['val_loss'].append(val_loss)
            self.history['lr'].append(current_lr)
            
            # Log progress
            logger.info(
                f"Epoch {epoch + 1}/{self.config.max_epochs} | "
                f"Train Loss: {train_loss:.6f} | "
                f"Val Loss: {val_loss:.6f} | "
                f"LR: {current_lr:.6e}"
            )
            
            # Early stopping check
            if val_loss < self.best_val_loss:
                self.best_val_loss = val_loss
                self.best_model_state = self.model.state_dict().copy()
                self.patience_counter = 0
                logger.info(f"✓ New best model (val_loss: {val_loss:.6f})")
            else:
                self.patience_counter += 1
                logger.info(f"Patience: {self.patience_counter}/{self.config.early_stopping_patience}")
                
                if self.patience_counter >= self.config.early_stopping_patience:
                    logger.info(f"Early stopping triggered at epoch {epoch + 1}")
                    break
        
        # Restore best model
        if self.best_model_state is not None:
            self.model.load_state_dict(self.best_model_state)
            logger.info(f"Restored best model with val_loss: {self.best_val_loss:.6f}")
        
        return self.history
    
    def evaluate(self) -> Dict:
        """
        Evaluate final model on validation set.
        
        Returns:
            Dictionary with metrics: {mse, mae, r2}
        """
        self.model.eval()
        all_predictions = []
        all_targets = []
        
        with torch.no_grad():
            for features, targets in self.val_loader:
                features = features.to(self.device)
                predictions = self.model(features)
                
                all_predictions.append(predictions.cpu().numpy())
                all_targets.append(targets.cpu().numpy())
        
        predictions = np.concatenate(all_predictions, axis=0).flatten()
        targets = np.concatenate(all_targets, axis=0).flatten()
        
        metrics = {
            'mse': mean_squared_error(targets, predictions),
            'mae': mean_absolute_error(targets, predictions),
            'r2': r2_score(targets, predictions)
        }
        
        logger.info(f"Validation Metrics: MSE={metrics['mse']:.4f}, MAE={metrics['mae']:.4f}, R²={metrics['r2']:.4f}")
        
        return metrics
    
    def save_artifacts(self, output_dir: str):
        """Save trained model and scaler."""
        os.makedirs(output_dir, exist_ok=True)
        
        # Save model
        model_path = os.path.join(output_dir, 'student_model.pth')
        torch.save(self.model.state_dict(), model_path)
        logger.info(f"Saved model to {model_path}")
        
        # Save scaler
        scaler_path = os.path.join(output_dir, 'scaler.pkl')
        with open(scaler_path, 'wb') as f:
            pickle.dump(self.scaler, f)
        logger.info(f"Saved scaler to {scaler_path}")
        
        # Save training history
        history_path = os.path.join(output_dir, 'training_history.json')
        with open(history_path, 'w') as f:
            json.dump(self.history, f, indent=2)
        logger.info(f"Saved training history to {history_path}")
        
        # Save config
        config_path = os.path.join(output_dir, 'training_config.json')
        with open(config_path, 'w') as f:
            json.dump(asdict(self.config), f, indent=2)
        logger.info(f"Saved config to {config_path}")


def load_and_preprocess_data(
    data_path: str,
    train_split: float = 0.8,
    random_seed: Optional[int] = None
) -> Tuple[DataLoader, DataLoader, StandardScaler]:
    """
    Load CSV data and create train/val dataloaders.
    
    Args:
        data_path: Path to training_data.csv
        train_split: Fraction of data for training (0.8 = 80%)
        random_seed: Random seed for reproducibility
        
    Returns:
        Tuple of (train_loader, val_loader, scaler)
    """
    if random_seed is not None:
        np.random.seed(random_seed)
        torch.manual_seed(random_seed)
    
    # Load data
    logger.info(f"Loading data from {data_path}")
    df = pd.read_csv(data_path)
    logger.info(f"Loaded {len(df)} samples")
    
    # Extract features and targets
    feature_cols = ['hour_sin', 'hour_cos', 'price_current', 'price_avg_4h', 'net_load', 'soc', 'dow_sin']
    target_col = 'power_setpoint'
    
    X = df[feature_cols].values
    y = df[target_col].values.reshape(-1, 1)
    
    # Time-series split (no shuffling)
    split_idx = int(len(df) * train_split)
    X_train, X_val = X[:split_idx], X[split_idx:]
    y_train, y_val = y[:split_idx], y[split_idx:]
    
    logger.info(f"Train set: {len(X_train)} samples (days 0-{split_idx // 96})")
    logger.info(f"Val set: {len(X_val)} samples (days {split_idx // 96}-365)")
    
    # Fit StandardScaler on training data only
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)
    
    logger.info(f"Feature scaling: mean={scaler.mean_}, std={scaler.scale_}")
    
    # Note: Targets (y) are NOT scaled - model outputs raw kW via Tanh × P_max
    
    # Convert to tensors
    train_dataset = TensorDataset(
        torch.FloatTensor(X_train_scaled),
        torch.FloatTensor(y_train)
    )
    val_dataset = TensorDataset(
        torch.FloatTensor(X_val_scaled),
        torch.FloatTensor(y_val)
    )
    
    # Create dataloaders
    train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=256, shuffle=False)
    
    return train_loader, val_loader, scaler


def train_student(
    data_path: str = 'data/training_data.csv',
    output_dir: str = 'artifacts',
    config: Optional[TrainingConfig] = None
) -> Dict:
    """
    Convenience function to train student model end-to-end.
    
    Args:
        data_path: Path to training data
        output_dir: Directory to save artifacts
        config: Training configuration (uses default if None)
        
    Returns:
        Dictionary with training results
    """
    if config is None:
        config = TrainingConfig()
    
    # Set random seed
    if config.random_seed is not None:
        np.random.seed(config.random_seed)
        torch.manual_seed(config.random_seed)
    
    # Load data
    train_loader, val_loader, scaler = load_and_preprocess_data(
        data_path,
        random_seed=config.random_seed
    )
    
    # Create model
    model = VPPStudentModel(input_dim=7, max_power=50.0)
    logger.info(f"Created model with {sum(p.numel() for p in model.parameters())} parameters")
    
    # Train
    trainer = Trainer(model, train_loader, val_loader, config, scaler)
    history = trainer.train()
    
    # Evaluate
    metrics = trainer.evaluate()
    
    # Save artifacts
    trainer.save_artifacts(output_dir)
    
    return {
        'history': history,
        'metrics': metrics,
        'config': asdict(config)
    }


if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='Train VPP Student Model')
    parser.add_argument('--data', type=str, default='data/training_data.csv', help='Path to training data')
    parser.add_argument('--output', type=str, default='artifacts', help='Output directory for artifacts')
    parser.add_argument('--epochs', type=int, default=100, help='Maximum epochs')
    parser.add_argument('--lr', type=float, default=1e-3, help='Learning rate')
    parser.add_argument('--batch-size', type=int, default=256, help='Batch size')
    parser.add_argument('--patience', type=int, default=10, help='Early stopping patience')
    
    args = parser.parse_args()
    
    config = TrainingConfig(
        max_epochs=args.epochs,
        learning_rate=args.lr,
        batch_size=args.batch_size,
        early_stopping_patience=args.patience
    )
    
    results = train_student(
        data_path=args.data,
        output_dir=args.output,
        config=config
    )
    
    print("\n" + "="*50)
    print("TRAINING COMPLETE")
    print("="*50)
    print(f"Best validation loss: {min(results['history']['val_loss']):.6f}")
    print(f"Final metrics: {results['metrics']}")
    print(f"Artifacts saved to: {args.output}")
